name: Test using Pytest in Docker

on: push

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      # Use GitHub's Docker registry to cache intermediate layers
      - run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
      - run: docker pull docker.pkg.github.com/$GITHUB_REPOSITORY/aleph-client-build-cache || true

      - name: Build the Docker image
        run: |
          git fetch --prune --unshallow --tags
          docker build . -t aleph-client:${GITHUB_REF##*/} -f docker/test.dockerfile --cache-from=docker.pkg.github.com/$GITHUB_REPOSITORY/aleph-client-build-cache

      - name: Push the image on GitHub's repository
        run: docker tag aleph-client:${GITHUB_REF##*/} docker.pkg.github.com/$GITHUB_REPOSITORY/aleph-client:${GITHUB_REF##*/} && docker push docker.pkg.github.com/$GITHUB_REPOSITORY/aleph-client:${GITHUB_REF##*/} || true

      - name: Cache the image on GitHub's repository
        run: docker tag aleph-client:${GITHUB_REF##*/} docker.pkg.github.com/$GITHUB_REPOSITORY/aleph-client-build-cache && docker push docker.pkg.github.com/$GITHUB_REPOSITORY/aleph-client-build-cache || true

      - name: Pytest in the Docker image
        run: |
          docker run aleph-client:${GITHUB_REF##*/} pytest

      - name: MyPy in the Docker image
        run: |
          docker run aleph-client:${GITHUB_REF##*/} mypy ./src/ --ignore-missing-imports
